// Engine as a module (NEXTJS-PLAN.md, step 1): joins the browser-free files of src/, in the order
// the plain page's build.mjs loads them, into web/engine/mx.mjs. The files keep their IIFE shape,
// so src/ merges from the plain page's branch as it is (B10); only this wrapper is new.
//   node web/engine/build.mjs          writes web/engine/mx.mjs (generated, not committed)
//   node web/engine/build.mjs --check  fails if a generated file is missing or older than src/
// The module is the same for the server and the browser. Each copy of the engine gets its own
// namespace object (installMX), whose prototype is the real global, so nothing leaks onto window.
// Step 2 adds two more generated files, for the pages (NEXTJS-PLAN.md, Layout of the repo):
//   web/engine/browser.mjs  the wrapped browser files (editor, store, grapher, stopwatch), unchanged,
//                           run on the real window by installBrowser(window) once MX is on it
//   web/engine/styles.css   src/styles.css, with the menus' `button` rules also matching links
//                           (the pages' navigation is real links now)
import { readFileSync, writeFileSync, readdirSync, existsSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..', '..');
const out = join(here, 'mx.mjs');
const outBrowser = join(here, 'browser.mjs');
const outStyles = join(here, 'styles.css');

// Every file build.mjs loads is one or the other. A new file upstream stops this build until
// someone says which (a file that touches the page at load time must not be in the module).
const ENGINE = ['core.js', 'texmath.js', 'parse.js', 'check.js', 'svg.js', 'helpers.js', 'verify.js', 'plot.js', 'flashcards.js'];
const BROWSER = ['editor.js', 'store.js', 'grapher.js', 'stopwatch.js', 'app.js'];
// app.js is carried over to the pages by hand (web/lib/app/app.mjs); the others are wrapped as they are
const REWRITTEN = ['app.js'];
// the menus whose `button` rules also style the links that replace those buttons
const LINK_MENUS = ['tabs', 'dnav', 'tut-tabs'];

// build.mjs's order, read from build.mjs itself so a reordering upstream is followed here
export function pageOrder() {
  const text = readFileSync(join(root, 'build.mjs'), 'utf8');
  const m = /const order = \[([^\]]*)\];/.exec(text);
  if (!m) throw new Error('web/engine/build.mjs: cannot find `const order = [...]` in build.mjs');
  const topics = readdirSync(join(root, 'src/topics')).filter((f) => f.endsWith('.js')).sort();
  const order = [];
  for (const raw of m[1].split(',').map((s) => s.trim()).filter(Boolean)) {
    const lit = /^'([\w./-]+)'$/.exec(raw);
    if (lit) order.push(lit[1]);
    else if (raw === "...topics.map((t) => 'topics/' + t)") order.push(...topics.map((t) => 'topics/' + t));
    else throw new Error('web/engine/build.mjs: unexpected entry in build.mjs order: ' + raw);
  }
  return order;
}

export function engineFiles() {
  const order = pageOrder();
  const unknown = order.filter((f) => !f.startsWith('topics/') && !ENGINE.includes(f) && !BROWSER.includes(f));
  if (unknown.length) throw new Error(`web/engine/build.mjs: build.mjs loads ${unknown.join(', ')}: add it to ENGINE or BROWSER here`);
  const missing = ENGINE.filter((f) => !order.includes(f));
  if (missing.length) throw new Error(`web/engine/build.mjs: build.mjs no longer loads ${missing.join(', ')}`);
  return order.filter((f) => !BROWSER.includes(f));
}

const sha = (s) => createHash('sha256').update(s).digest('hex');

export function build() {
  const files = engineFiles();
  const sources = files.map((f) => [f, readFileSync(join(root, 'src', f), 'utf8')]);
  const hashes = Object.fromEntries(sources.map(([f, s]) => [f, sha(s)]));
  const body = sources.map(([f, s]) => `/* ---- ${f} ---- */\n${s}`).join('\n');
  const text = `// GENERATED by web/engine/build.mjs from src/: do not edit (run \`node web/engine/build.mjs\`).
// The browser-free part of the engine (core, math, checking, every topic, the flashcards).
/* eslint-disable */
export const FILES = ${JSON.stringify(files)};
export const SOURCE_SHA256 = ${JSON.stringify(hashes, null, 0)};

function load(window) {
${body}
}

/** Runs the engine's files with \`G\` as their global and returns G.MX (G gets MX and nothing else). */
export function installMX(G) {
  load(G);
  return G.MX;
}

/** A fresh, independent copy of the engine. */
export function createMX() {
  return installMX(Object.create(globalThis));
}

/** The shared copy. */
export const MX = createMX();
export default MX;
`;
  return { text, files, hashes };
}

// the browser files, in build.mjs's order, as one function that runs them on the window it is given
export function buildBrowser() {
  const files = pageOrder().filter((f) => BROWSER.includes(f) && !REWRITTEN.includes(f));
  const sources = files.map((f) => [f, readFileSync(join(root, 'src', f), 'utf8')]);
  const body = sources.map(([f, s]) => `/* ---- ${f} ---- */\n${s}`).join('\n');
  const text = `// GENERATED by web/engine/build.mjs from src/: do not edit (run \`node web/engine/build.mjs\`).
// The plain page's browser files (${files.join(', ')}), unchanged. installBrowser(window) runs them
// on the real window, which must already have the engine as window.MX; call it once per page load.
/* eslint-disable */
export const FILES = ${JSON.stringify(files)};

export function installBrowser(window) {
${body}
  return window.MX;
}
`;
  return { text, files };
}

// src/styles.css for the pages: rules written for the menus' <button>s match their <a>s too
export function buildStyles() {
  const css = readFileSync(join(root, 'src', 'styles.css'), 'utf8');
  const re = new RegExp(`(\\.(?:${LINK_MENUS.join('|')}))(\\s+)button\\b`, 'g');
  let n = 0;
  const text = `/* GENERATED by web/engine/build.mjs from src/styles.css: do not edit. The menus' button rules\n   (${LINK_MENUS.map((m) => '.' + m).join(', ')}) also match links: :is(button, a). */\n` +
    css.replace(re, (m, sel, sp) => { n++; return `${sel}${sp}:is(button, a)`; });
  if (!n) throw new Error('web/engine/build.mjs: no menu button rules found in src/styles.css');
  return { text, rules: n };
}

const isMain = process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1];
if (isMain) {
  const { text, files } = build();
  const br = buildBrowser();
  const st = buildStyles();
  const outs = [[out, text], [outBrowser, br.text], [outStyles, st.text]];
  if (process.argv.includes('--check')) {
    const stale = outs.filter(([f, t]) => (existsSync(f) ? readFileSync(f, 'utf8') : '') !== t).map(([f]) => f.replace(/^.*\/web\//, 'web/'));
    if (stale.length) { console.error(`${stale.join(', ')}: missing or out of date: run node web/engine/build.mjs`); process.exit(1); }
    console.log('web/engine/mx.mjs, browser.mjs and styles.css are up to date');
  } else {
    for (const [f, t] of outs) writeFileSync(f, t);
    console.log(`built web/engine/mx.mjs (${files.length} files, ${(text.length / 1024).toFixed(0)} KB), browser.mjs (${br.files.length} files), styles.css (${st.rules} menu rules)`);
  }
}
