/* flashcards.js: rule cards for every topic. Each card is [front, back]; math uses \( \). */
(function (G) {
  'use strict';
  const MX = G.MX;
  const T = MX.T;
  MX.FLASH = {
    // ---------------- Polynomials & exponents ----------------
    'poly-addsub': [
      [T`Like terms`, T`Terms with the same variables raised to the same powers, like \(4x^{2}\) and \(-7x^{2}\). Only like terms combine.`],
      [T`Combining like terms`, T`Add the coefficients and keep the variable part: \(5x^{2} + 3x^{2} = 8x^{2}\).`],
      [T`Subtracting a polynomial`, T`Distribute the minus sign to <em>every</em> term: \(-\left(3x^{2} - 2x + 1\right) = -3x^{2} + 2x - 1\).`],
      [T`\(\left(a\right) - k\left(b\right)\)`, T`Multiply every term of \(b\) by \(-k\) first, then combine like terms.`],
      [T`Standard form of a polynomial`, T`Terms from the highest power to the lowest: \(6x^{2} - 4x - 2\).`],
      [T`\(\left(15x^{2} - 7x + 4\right) - \left(9x^{2} - 3x + 6\right)\)`, T`\(6x^{2} - 4x - 2\)`],
    ],
    'poly-divmono': [
      [T`Dividing a polynomial by a monomial`, T`Divide each term separately: \(\dfrac{a + b}{d} = \dfrac{a}{d} + \dfrac{b}{d}\).`],
      [T`Quotient rule for exponents`, T`\(\dfrac{x^{m}}{x^{n}} = x^{m - n}\)`],
      [T`\(\dfrac{12m^{4}n^{5}}{4m^{3}n^{3}}\)`, T`\(3mn^{2}\)`],
      [T`A negative exponent in the result`, T`Move that factor to the denominator: \(m^{-2}n^{-2} = \dfrac{1}{m^{2}n^{2}}\).`],
      [T`Dividing by a negative monomial`, T`Every term changes sign: \(\dfrac{20x^{7} - 4x^{3}}{-4x^{3}} = -5x^{4} + 1\).`],
    ],
    'special-products': [
      [T`\(\left(a - b\right)\left(a + b\right)\)`, T`\(a^{2} - b^{2}\) (the middle terms cancel)`],
      [T`\(\left(a + b\right)^{2}\)`, T`\(a^{2} + 2ab + b^{2}\)`],
      [T`\(\left(a - b\right)^{2}\)`, T`\(a^{2} - 2ab + b^{2}\)`],
      [T`\(\left(\sqrt{y} - \sqrt{5}\right)\left(\sqrt{y} + \sqrt{5}\right)\)`, T`\(y - 5\), because \(\left(\sqrt{y}\right)^{2} = y\)`],
      [T`FOIL`, T`First, Outer, Inner, Last: multiply each term of the first binomial by each term of the second.`],
      [T`Is \(\left(a + b\right)^{2} = a^{2} + b^{2}\)?`, T`No. Don't forget the middle term \(2ab\).`],
    ],
    'exp-rules': [
      [T`Product rule`, T`\(x^{m}\cdot x^{n} = x^{m + n}\)`],
      [T`Quotient rule`, T`\(\dfrac{x^{m}}{x^{n}} = x^{m - n}\)`],
      [T`Power rule`, T`\(\left(x^{m}\right)^{n} = x^{mn}\)`],
      [T`Power of a product`, T`\(\left(xy\right)^{n} = x^{n}y^{n}\)`],
      [T`Zero exponent`, T`\(x^{0} = 1\) (for \(x \ne 0\))`],
      [T`Negative exponent`, T`\(x^{-n} = \dfrac{1}{x^{n}}\) and \(\dfrac{1}{x^{-n}} = x^{n}\)`],
      [T`\(\left(m^{4}n^{3}\right)^{-2}\left(m^{5}n^{0}\right)^{3}\)`, T`\(\dfrac{m^{7}}{n^{6}}\)`],
    ],
    'sci-notation': [
      [T`Form of scientific notation`, T`\(a \times 10^{n}\) with \(1 \le a \lt 10\) and \(n\) an integer`],
      [T`Large number → scientific notation`, T`Move the decimal left; the exponent is positive: \(396{,}710 = 3.9671 \times 10^{5}\).`],
      [T`Small number → scientific notation`, T`Move the decimal right; the exponent is negative: \(0.00045 = 4.5 \times 10^{-4}\).`],
      [T`Multiplying`, T`Multiply the front numbers, add the exponents, then adjust: \(33.58 \times 10^{6} = 3.358 \times 10^{7}\).`],
      [T`Dividing`, T`Divide the front numbers, subtract the exponents, then adjust.`],
      [T`Adjusting the front number`, T`10 or more: move the decimal left, add 1 to the exponent. Below 1: move it right, subtract 1.`],
    ],
    'signed-powers': [
      [T`\(-2^{4}\)`, T`\(-16\): the exponent applies only to the 2.`],
      [T`\(\left(-2\right)^{4}\)`, T`\(16\): an even number of negative factors is positive.`],
      [T`\(\left(-2\right)^{3}\)`, T`\(-8\): an odd number of negative factors is negative.`],
      [T`\(-\left(-2\right)^{3}\)`, T`\(8\)`],
      [T`A negative sign in front of a power`, T`Do the power first, then apply the negative (unless the negative is inside the parentheses).`],
    ],
    // ---------------- Factoring ----------------
    'factor-trinomial': [
      [T`First step in any factoring problem`, T`Take out the greatest common factor (GCF).`],
      [T`Factoring \(x^{2} + bx + c\)`, T`Find two numbers that multiply to \(c\) and add to \(b\).`],
      [T`AC method for \(ax^{2} + bx + c\)`, T`Find two numbers that multiply to \(ac\) and add to \(b\), split the middle term, then factor by grouping.`],
      [T`\(5r^{2} + 12r + 4\)`, T`\(\left(5r + 2\right)\left(r + 2\right)\)`],
      [T`\(3x^{2} + 6x - 9\)`, T`\(3\left(x + 3\right)\left(x - 1\right)\)`],
      [T`How do you check a factorization?`, T`Multiply the factors back out; you should get the original.`],
    ],
    'factor-grouping': [
      [T`When should you try grouping?`, T`When there are four terms.`],
      [T`Grouping steps`, T`Pair the terms, factor the GCF from each pair, then factor out the common binomial.`],
      [T`\(ab + 5b + 2a + 10\)`, T`\(b\left(a + 5\right) + 2\left(a + 5\right) = \left(a + 5\right)\left(b + 2\right)\)`],
      [T`The second pair starts with a minus`, T`Factor out a negative so the binomials match: \(x^{2}\left(x + 3\right) - 4\left(x + 3\right)\).`],
      [T`After grouping`, T`Check whether a factor still factors, like \(x^{2} - 4 = \left(x - 2\right)\left(x + 2\right)\).`],
    ],
    'factor-special': [
      [T`Difference of squares`, T`\(a^{2} - b^{2} = \left(a - b\right)\left(a + b\right)\)`],
      [T`Difference of cubes`, T`\(a^{3} - b^{3} = \left(a - b\right)\left(a^{2} + ab + b^{2}\right)\)`],
      [T`Sum of cubes`, T`\(a^{3} + b^{3} = \left(a + b\right)\left(a^{2} - ab + b^{2}\right)\)`],
      [T`Perfect-square trinomial`, T`\(a^{2} \pm 2ab + b^{2} = \left(a \pm b\right)^{2}\)`],
      [T`SOAP`, T`Signs in the cube formulas: <strong>S</strong>ame, <strong>O</strong>pposite, <strong>A</strong>lways <strong>P</strong>ositive.`],
      [T`Sum of squares \(a^{2} + b^{2}\)`, T`Prime: it doesn't factor.`],
      [T`Perfect cubes to know`, T`1, 8, 27, 64, 125, 216, 343, 512, 729, 1000`],
      [T`\(x^{4} - 16\)`, T`\(\left(x^{2} + 4\right)\left(x - 2\right)\left(x + 2\right)\)`],
      [T`\(8x^{3} - 27\)`, T`\(\left(2x - 3\right)\left(4x^{2} + 6x + 9\right)\)`],
      [T`\(x^{3} + 64\)`, T`\(\left(x + 4\right)\left(x^{2} - 4x + 16\right)\)`],
      [T`\(x^{2} + 10x + 25\)`, T`\(\left(x + 5\right)^{2}\)`],
    ],
    'factor-strategy': [
      [T`Factoring checklist: step 1`, T`Take out the GCF.`],
      [T`Two terms`, T`Difference of squares, difference of cubes, or sum of cubes. A sum of squares is prime.`],
      [T`Three terms`, T`Perfect-square trinomial, or the trinomial (AC) method.`],
      [T`Four terms`, T`Factor by grouping.`],
      [T`Last step`, T`Check every factor again; keep going until nothing factors.`],
      [T`Prime polynomial`, T`One that can't be factored, like \(x^{2} + 3x + 7\) or \(x^{2} + 9\).`],
      [T`\(3x^{3} - 12x\)`, T`\(3x\left(x - 2\right)\left(x + 2\right)\)`],
    ],
    // ---------------- Rational expressions ----------------
    'rat-simplify': [
      [T`Simplifying a rational expression`, T`Factor the top and bottom completely, then cancel common factors.`],
      [T`Can you cancel the 5s in \(\dfrac{x + 5}{5}\)?`, T`No. Cancel factors, never terms.`],
      [T`\(\dfrac{a - b}{b - a}\)`, T`\(-1\) (opposites)`],
      [T`\(\dfrac{x^{2} - 25}{x - 5}\)`, T`\(x + 5\)`],
      [T`Restrictions`, T`Values that make the original denominator 0 are excluded.`],
    ],
    'rat-divide': [
      [T`Multiplying rational expressions`, T`Factor, cancel, then multiply the tops and the bottoms.`],
      [T`Dividing rational expressions`, T`Multiply by the reciprocal: \(\dfrac{A}{B}\div\dfrac{C}{D} = \dfrac{A}{B}\cdot\dfrac{D}{C}\).`],
      [T`\(\dfrac{6}{w - 3}\div\dfrac{36}{3 - w}\)`, T`\(-\dfrac{1}{6}\)`],
      [T`\(\dfrac{w - 3}{3 - w}\)`, T`\(-1\)`],
    ],
    'rat-addsub': [
      [T`Adding or subtracting rational expressions`, T`Rewrite over a common denominator (LCD), then combine the numerators.`],
      [T`Least common denominator (LCD)`, T`Every factor of the denominators, each to its highest power.`],
      [T`Subtracting a numerator`, T`Put it in parentheses: \(-\left(w - 5\right) = -w + 5\).`],
      [T`\(\dfrac{2}{k + 4} - \dfrac{1}{k}\)`, T`\(\dfrac{k - 4}{k\left(k + 4\right)}\)`],
      [T`After combining`, T`Factor the numerator and cancel if you can.`],
    ],
    'rat-equation': [
      [T`Solving a rational equation`, T`Multiply every term by the LCD to clear the fractions.`],
      [T`Extraneous solution`, T`A value that makes a denominator 0. Throw it out.`],
      [T`Proportion shortcut`, T`\(\dfrac{a}{b} = \dfrac{c}{d} \Rightarrow ad = bc\)`],
      [T`Every candidate is extraneous`, T`The answer is <em>no solution</em>.`],
      [T`\(\dfrac{x + 5}{x} + \dfrac{3}{4} = \dfrac{1}{2}\)`, T`\(x = -4\)`],
    ],
    // ---------------- Radicals ----------------
    'rad-simplify': [
      [T`Product rule for radicals`, T`\(\sqrt{ab} = \sqrt{a}\sqrt{b}\)`],
      [T`Simplifying \(\sqrt{n}\)`, T`Pull out the largest perfect-square factor: \(\sqrt{50} = \sqrt{25\cdot2} = 5\sqrt{2}\).`],
      [T`\(\sqrt{x^{12}}\)`, T`\(x^{6}\) (half the exponent)`],
      [T`\(\sqrt{t^{13}}\)`, T`\(t^{6}\sqrt{t}\)`],
      [T`Perfect squares to know`, T`1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144`],
      [T`\(\sqrt{75x^{12}y^{5}}\)`, T`\(5x^{6}y^{2}\sqrt{3y}\)`],
    ],
    'rad-addsub': [
      [T`Like radicals`, T`Same index and same number inside, like \(5\sqrt{7}\) and \(-6\sqrt{7}\).`],
      [T`Adding like radicals`, T`Add the coefficients: \(5\sqrt{7} - 6\sqrt{7} = -\sqrt{7}\).`],
      [T`Before adding radicals`, T`Simplify each one first; they may turn out to be like radicals.`],
      [T`Is \(\sqrt{a} + \sqrt{b} = \sqrt{a + b}\)?`, T`No.`],
      [T`\(\sqrt{175} - \sqrt{252}\)`, T`\(5\sqrt{7} - 6\sqrt{7} = -\sqrt{7}\)`],
    ],
    'rad-quadexpr': [
      [T`Simplifying \(\dfrac{a \pm \sqrt{b}}{c}\)`, T`Simplify the radical, then divide every term by a common factor.`],
      [T`\(\dfrac{-6 \pm \sqrt{90}}{9}\)`, T`\(\dfrac{-2 \pm \sqrt{10}}{3}\)`],
      [T`Can you cancel one term with the denominator?`, T`No. A factor must divide every term: the number, the radical's coefficient and the denominator.`],
      [T`What \(\pm\) means`, T`Two answers: one with +, one with −.`],
    ],
    'rad-ratexp': [
      [T`\(\sqrt[n]{x^{m}}\)`, T`\(x^{m/n}\)`],
      [T`\(\sqrt{x}\) as an exponent`, T`\(x^{1/2}\)`],
      [T`\(\sqrt[8]{D^{3}}\)`, T`\(D^{3/8}\)`],
      [T`\(\left(\sqrt[n]{x}\right)^{m}\)`, T`Also \(x^{m/n}\)`],
      [T`In \(x^{m/n}\), which number is the root?`, T`The denominator \(n\). The numerator \(m\) is the power.`],
    ],
    'rad-equation': [
      [T`Solving a radical equation`, T`Isolate the radical, square both sides, solve, then check.`],
      [T`\(\sqrt{\ \ } =\) a negative number`, T`No solution: a principal square root is never negative.`],
      [T`Why check your answers?`, T`Squaring can create extraneous solutions.`],
      [T`\(\sqrt{5x - 6} = \sqrt{x}\)`, T`\(5x - 6 = x\), so \(x = \frac{3}{2}\)`],
      [T`\(\sqrt{3t - 7} = 4\)`, T`\(3t - 7 = 16\), so \(t = \frac{23}{3}\)`],
    ],
    // ---------------- Equations & inequalities ----------------
    'lin-equation': [
      [T`Order of steps for a linear equation`, T`Clear fractions, distribute, collect the \(x\) terms, divide.`],
      [T`Clearing fractions`, T`Multiply every term on both sides by the LCD.`],
      [T`Checking a solution`, T`Substitute it into the original equation.`],
      [T`\(3\left(6 - 2x\right) = -4x\)`, T`\(x = 9\)`],
      [T`\(\dfrac{x}{3} - 5 = \dfrac{x}{4} - 2\)`, T`\(x = 36\)`],
    ],
    'literal': [
      [T`Solving a formula for a variable`, T`Treat the other letters like numbers and undo operations in reverse order.`],
      [T`The variable is multiplied by a group`, T`Divide by the whole group, keeping it in parentheses.`],
      [T`\(P = 2l + 2w\) for \(w\)`, T`\(w = \dfrac{P - 2l}{2}\)`],
      [T`\(K = \dfrac{ma}{F}\) for \(m\)`, T`\(m = \dfrac{KF}{a}\)`],
      [T`\(n = \dfrac{2A}{B + d}\) for \(A\)`, T`\(A = \dfrac{n\left(B + d\right)}{2}\)`],
    ],
    'lin-inequality': [
      [T`Multiplying or dividing an inequality by a negative`, T`Flip the inequality sign.`],
      [T`Closed dot on a number line`, T`\(\le\) or \(\ge\): the endpoint is included.`],
      [T`Open dot on a number line`, T`\(\lt\) or \(\gt\): the endpoint is not included.`],
      [T`\(x \ge -3\) in interval notation`, T`\([-3, \infty)\)`],
      [T`\(-\frac{1}{3}x + 2 \le 3\)`, T`\(x \ge -3\)`],
    ],
    'exp-equation': [
      [T`One-to-one property of exponents`, T`If \(b^{M} = b^{N}\), then \(M = N\).`],
      [T`Steps for a same-base exponential equation`, T`Write both sides as powers of the same base, set the exponents equal, solve.`],
      [T`Powers of 2`, T`2, 4, 8, 16, 32, 64, 128, 256`],
      [T`Powers of 3`, T`3, 9, 27, 81, 243, 729`],
      [T`\(\frac{1}{27}\) as a power of 3`, T`\(3^{-3}\)`],
      [T`\(5^{7 - 2x} = 25\)`, T`\(7 - 2x = 2\), so \(x = \frac{5}{2}\)`],
    ],
    'quad-factor': [
      [T`Zero-product property`, T`If \(AB = 0\), then \(A = 0\) or \(B = 0\).`],
      [T`Before factoring a quadratic equation`, T`Get 0 on one side.`],
      [T`Why not divide both sides by \(x\)?`, T`You'd lose the solution \(x = 0\). Factor \(x\) out instead.`],
      [T`\(t^{2} - 2t - 15 = 0\)`, T`\(t = 5\) or \(t = -3\)`],
      [T`\(4x^{2} - 16x = 0\)`, T`\(x = 0\) or \(x = 4\)`],
    ],
    'quad-sqrt': [
      [T`Square root property`, T`If \(u^{2} = k\), then \(u = \pm\sqrt{k}\).`],
      [T`The most common mistake`, T`Forgetting the \(\pm\): there are two answers.`],
      [T`\(\left(3k + 2\right)^{2} = 49\)`, T`\(k = \frac{5}{3}\) or \(k = -3\)`],
      [T`\(2x^{2} - 90 = 0\)`, T`\(x = \pm 3\sqrt{5}\)`],
      [T`When to use the square root property`, T`When the equation is (something)\(^{2}\) = a number, with no separate \(x\) term.`],
    ],
    'quad-formula': [
      [T`Quadratic formula`, T`\(x = \dfrac{-b \pm \sqrt{b^{2} - 4ac}}{2a}\)`],
      [T`Before using the formula`, T`Write the equation as \(ax^{2} + bx + c = 0\).`],
      [T`Discriminant \(b^{2} - 4ac\)`, T`Positive: 2 real solutions. Zero: 1. Negative: no real solutions.`],
      [T`The discriminant is a perfect square`, T`The answers are rational (the quadratic factors).`],
      [T`\(2x^{2} - 3x - 5 = 0\)`, T`\(x = \frac{5}{2}\) or \(x = -1\)`],
    ],
    // ---------------- Logarithms ----------------
    'log-form': [
      [T`Definition of a logarithm`, T`\(\log_{b} N = k \iff b^{k} = N\)`],
      [T`\(\log_{2} 32 = 5\) in exponential form`, T`\(2^{5} = 32\)`],
      [T`\(3^{4} = 81\) in logarithmic form`, T`\(\log_{3} 81 = 4\)`],
      [T`Common log \(\log N\)`, T`Base 10: \(\log 1000 = 3\).`],
      [T`Natural log \(\ln N\)`, T`Base \(e \approx 2.718\).`],
      [T`\(e^{x} = 7\) in logarithmic form`, T`\(\ln 7 = x\)`],
    ],
    'log-eval': [
      [T`How to evaluate \(\log_{b} N\)`, T`Ask: \(b\) to what power gives \(N\)?`],
      [T`\(\log_{b} 1\)`, T`\(0\)`],
      [T`\(\log_{b} b\)`, T`\(1\)`],
      [T`\(\log_{b} b^{k}\)`, T`\(k\)`],
      [T`\(b^{\log_{b} N}\)`, T`\(N\)`],
      [T`\(\ln e^{k}\) and \(e^{\ln N}\)`, T`\(k\) and \(N\)`],
      [T`\(\log_{2} \frac{1}{8}\)`, T`\(-3\)`],
      [T`\(\log_{9} 3\)`, T`\(\frac{1}{2}\)`],
    ],
    'log-expand': [
      [T`Product rule for logs`, T`\(\log_{b}\left(MN\right) = \log_{b} M + \log_{b} N\)`],
      [T`Quotient rule for logs`, T`\(\log_{b}\dfrac{M}{N} = \log_{b} M - \log_{b} N\)`],
      [T`Power rule for logs`, T`\(\log_{b} M^{p} = p\log_{b} M\)`],
      [T`\(\log\sqrt{x}\)`, T`\(\frac{1}{2}\log x\)`],
      [T`\(\log\left(M + N\right)\)`, T`Doesn't split: there is no rule for the log of a sum.`],
      [T`\(\ln\dfrac{x^{3}y}{z^{2}}\)`, T`\(3\ln x + \ln y - 2\ln z\)`],
    ],
    'log-condense': [
      [T`Condensing logs`, T`Use the log rules backward to write one single log.`],
      [T`First step when condensing`, T`Power rule: move each coefficient up as an exponent.`],
      [T`Logs that are added`, T`Combine by multiplying inside one log.`],
      [T`Logs that are subtracted`, T`Their insides go in the denominator.`],
      [T`\(2\log x + 3\log y - \log z\)`, T`\(\log\dfrac{x^{2}y^{3}}{z}\)`],
      [T`\(2 + \log_{3} x\)`, T`\(2 = \log_{3} 9\), so it's \(\log_{3}\left(9x\right)\).`],
    ],
    'log-cob': [
      [T`Change-of-base formula`, T`\(\log_{b} N = \dfrac{\ln N}{\ln b} = \dfrac{\log N}{\log b}\)`],
      [T`Which log goes on top?`, T`The log of the number \(N\). The log of the base goes on the bottom.`],
      [T`\(\log_{3} 20\)`, T`\(\dfrac{\ln 20}{\ln 3} \approx 2.73\)`],
      [T`When is \(\log_{b} N\) negative (for \(b \gt 1\))?`, T`When \(0 \lt N \lt 1\).`],
    ],
    'log-solve': [
      [T`One log equals a number`, T`Rewrite in exponential form.`],
      [T`A log equals a log (same base)`, T`Set the insides equal.`],
      [T`Several logs on one side`, T`Condense them into one log first.`],
      [T`Checking log answers`, T`The inside of every log must be positive; reject extraneous answers.`],
      [T`\(\log_{2}\left(x + 3\right) = 5\)`, T`\(x + 3 = 32\), so \(x = 29\)`],
      [T`\(\log_{2} x + \log_{2}\left(x - 2\right) = 3\)`, T`\(x = 4\) (\(x = -2\) is extraneous)`],
    ],
    'log-expeq': [
      [T`Solving \(b^{x} = N\) when \(N\) isn't a power of \(b\)`, T`Take \(\ln\) of both sides: \(x = \dfrac{\ln N}{\ln b}\).`],
      [T`\(5^{x} = 12\)`, T`\(x = \dfrac{\ln 12}{\ln 5} \approx 1.54\)`],
      [T`\(e^{3x} = 20\)`, T`\(3x = \ln 20\), so \(x = \dfrac{\ln 20}{3} \approx 1.00\)`],
      [T`First step for \(3\cdot 2^{x} + 1 = 25\)`, T`Isolate the power: \(2^{x} = 8\).`],
      [T`Is \(\dfrac{\ln 12}{\ln 5} = \ln\dfrac{12}{5}\)?`, T`No. A quotient of logs is not the log of a quotient.`],
    ],
    // ---------------- Graphs, lines & systems ----------------
    'line-standard': [
      [T`x-intercept`, T`Set \(y = 0\) and solve. The point is \((x, 0)\).`],
      [T`y-intercept`, T`Set \(x = 0\) and solve. The point is \((0, y)\).`],
      [T`Slope-intercept form`, T`\(y = mx + b\): \(m\) is the slope, \(b\) the y-intercept.`],
      [T`Standard form of a line`, T`\(Ax + By = C\)`],
      [T`\(4x - 3y = -1\) in slope-intercept form`, T`\(y = \frac{4}{3}x + \frac{1}{3}\)`],
      [T`Graphing from standard form`, T`Plot both intercepts and draw the line through them.`],
    ],
    'line-two-points': [
      [T`Slope formula`, T`\(m = \dfrac{y_{2} - y_{1}}{x_{2} - x_{1}}\)`],
      [T`Finding \(b\)`, T`Substitute \(m\) and one point into \(y = mx + b\).`],
      [T`Parallel lines`, T`Same slope.`],
      [T`Perpendicular lines`, T`Negative reciprocal slopes: \(-\frac{5}{3} \to \frac{3}{5}\).`],
      [T`Slope of a horizontal line; of a vertical line`, T`Horizontal: slope 0. Vertical: no slope at all (the run is 0, and you can't divide by 0).`],
    ],
    'parabola': [
      [T`x-intercepts of \(y = ax^{2} + bx + c\)`, T`Set \(y = 0\) and solve.`],
      [T`y-intercept of \(y = ax^{2} + bx + c\)`, T`\((0, c)\)`],
      [T`Vertex x-coordinate`, T`\(x = -\dfrac{b}{2a}\); plug it in to get \(y\).`],
      [T`Does it open up or down?`, T`Up if \(a \gt 0\), down if \(a \lt 0\).`],
      [T`Vertex and x-intercepts`, T`The vertex is halfway between the x-intercepts.`],
      [T`\(y = x^{2} - 4x + 3\)`, T`x-intercepts \((1, 0)\), \((3, 0)\); y-intercept \((0, 3)\); vertex \((2, -1)\)`],
    ],
    'systems': [
      [T`Elimination method`, T`Multiply so one variable's coefficients are opposites, add, solve, then substitute back.`],
      [T`Substitution method`, T`Solve one equation for a variable and substitute into the other.`],
      [T`Decimals in a system`, T`Multiply that equation by 10 or 100 first.`],
      [T`Answer format`, T`An ordered pair \((x, y)\). Check it in both equations.`],
      [T`\(0 = 5\) or \(0 = 0\) after eliminating`, T`No solution (parallel lines) or infinitely many (the same line).`],
    ],
    'variation': [
      [T`Direct variation`, T`\(y = kx\)`],
      [T`Inverse variation`, T`\(y = \dfrac{k}{x}\)`],
      [T`\(y\) varies directly as the square of \(x\)`, T`\(y = kx^{2}\)`],
      [T`Solving a variation problem`, T`Write the model, use the given pair to find \(k\), then answer the question.`],
      [T`\(x\) varies inversely as \(p\); \(x = 50\) when \(p = 2\)`, T`\(k = 100\), so \(x = \dfrac{100}{p}\)`],
    ],
    // ---------------- Relations & functions ----------------
    'rel-function': [
      [T`Relation`, T`Any set of ordered pairs.`],
      [T`Function`, T`A relation where each input \(x\) has exactly one output \(y\).`],
      [T`Vertical line test`, T`If any vertical line crosses the graph more than once, it isn't a function.`],
      [T`Can a function repeat a \(y\)-value?`, T`Yes. Outputs may repeat; an input can't have two outputs.`],
      [T`Circle, sideways parabola, vertical line`, T`Not functions.`],
      [T`Mapping diagram test`, T`Not a function if any input has two arrows leaving it.`],
    ],
    'rel-dr': [
      [T`Domain`, T`The set of all inputs (\(x\)-values).`],
      [T`Range`, T`The set of all outputs (\(y\)-values).`],
      [T`Writing a set`, T`Braces, each value once: \(\{-2, 0, 3\}\).`],
      [T`\(\{(1, 3), (2, 5), (1, 7)\}\)`, T`Domain \(\{1, 2\}\), range \(\{3, 5, 7\}\)`],
    ],
    'fn-graph-dr': [
      [T`Closed dot ●`, T`The endpoint is included: bracket \([\ ]\).`],
      [T`Open dot ○`, T`The endpoint is not included: parenthesis \((\ )\).`],
      [T`An arrow on a graph`, T`It keeps going: \(\infty\) or \(-\infty\), always with a parenthesis.`],
      [T`All real numbers in interval notation`, T`\((-\infty, \infty)\)`],
      [T`Reading domain and range from a graph`, T`Domain: left to right along the \(x\)-axis. Range: bottom to top along the \(y\)-axis.`],
      [T`\(-3 \le x \lt 5\) in interval notation`, T`\([-3, 5)\)`],
    ],
    'fn-domain': [
      [T`Domain of a polynomial`, T`All real numbers, \((-\infty, \infty)\).`],
      [T`Domain of a fraction`, T`Exclude values that make the denominator 0.`],
      [T`Domain of a square root`, T`The inside must be \(\ge 0\).`],
      [T`Square root in a denominator`, T`The inside must be \(\gt 0\).`],
      [T`\(f(x) = \dfrac{1}{x - 3}\)`, T`\((-\infty, 3) \cup (3, \infty)\)`],
      [T`\(f(x) = \sqrt{2x - 6}\)`, T`\([3, \infty)\)`],
    ],
    'fn-range': [
      [T`Range of a non-horizontal line`, T`All real numbers.`],
      [T`Range of \(a\left(x - h\right)^{2} + k\)`, T`\([k, \infty)\) if \(a \gt 0\); \((-\infty, k]\) if \(a \lt 0\).`],
      [T`Range of \(a\sqrt{x - h} + k\)`, T`\([k, \infty)\) if \(a \gt 0\); \((-\infty, k]\) if \(a \lt 0\).`],
      [T`Range of \(a\left|x - h\right| + k\)`, T`Same idea: the V's point is at \(y = k\).`],
      [T`Range of a parabola in standard form`, T`Find the vertex with \(x = -\frac{b}{2a}\), then the vertex's \(y\) is the minimum or maximum.`],
    ],
    // ---------------- Word problems ----------------
    'w-proportion': [
      [T`Proportion`, T`Two equal ratios: \(\dfrac{a}{b} = \dfrac{c}{d}\).`],
      [T`Setting up a proportion`, T`Put the same units in the same places, like grams over cakes on both sides.`],
      [T`Cross-multiplying`, T`\(\dfrac{a}{b} = \dfrac{c}{d} \Rightarrow ad = bc\)`],
      [T`Unit rate method`, T`Find the amount for one, then multiply.`],
      [T`Tax is $2.89 on $34. Tax on $98?`, T`\(\dfrac{2.89}{34} = \dfrac{x}{98}\), so \(x \approx \$8.33\)`],
    ],
    'w-percent': [
      [T`Percent → decimal`, T`Divide by 100: 18% = 0.18.`],
      [T`What percent is the part of the whole?`, T`\(\dfrac{\text{part}}{\text{whole}}\times100\)`],
      [T`A percent of a number`, T`decimal × number`],
      [T`Percent change`, T`\(\dfrac{\text{new} - \text{old}}{\text{old}}\times100\)`],
      [T`Finding the whole`, T`whole = part ÷ decimal`],
      [T`Sale price after \(p\)% off`, T`price × \(\left(1 - \frac{p}{100}\right)\)`],
    ],
    'w-sci': [
      [T`"Total" problems`, T`Count × amount each: multiply.`],
      [T`"Per person" or "how long" problems`, T`Divide.`],
      [T`Multiplying in scientific notation`, T`Multiply the fronts, add the exponents, adjust.`],
      [T`\(320{,}000 \times 41{,}000\)`, T`\(\left(3.2\times10^{5}\right)\left(4.1\times10^{4}\right) = 1.312\times10^{10}\)`],
      [T`Dividing in scientific notation`, T`Divide the fronts, subtract the exponents, adjust.`],
    ],
    'w-ineq': [
      [T`at least, minimum`, T`\(\ge\)`],
      [T`at most, maximum, no more than`, T`\(\le\)`],
      [T`more than, exceeds`, T`\(\gt\)`],
      [T`less than, fewer than`, T`\(\lt\)`],
      [T`Budget problems`, T`fixed cost + rate × \(x\) \(\le\) budget`],
      [T`Average needed`, T`\(\dfrac{\text{sum} + x}{n} \ge\) target`],
    ],
    'w-perimeter': [
      [T`Perimeter of a rectangle`, T`\(P = 2l + 2w\)`],
      [T`Area of a rectangle`, T`\(A = lw\)`],
      [T`"5 less than three times the width"`, T`\(3w - 5\)`],
      [T`Fence on three sides (a barn is the fourth)`, T`\(2w + l\) = total fencing`],
      [T`Area word problems`, T`Lead to quadratics; keep the positive answer.`],
      [T`Units`, T`Perimeter uses plain units (inches); area uses square units.`],
    ],
    'w-pyth': [
      [T`Pythagorean theorem`, T`\(a^{2} + b^{2} = c^{2}\), where \(c\) is the hypotenuse.`],
      [T`Hypotenuse`, T`The longest side, across from the right angle.`],
      [T`Finding a leg`, T`\(b = \sqrt{c^{2} - a^{2}}\)`],
      [T`Common Pythagorean triples`, T`3-4-5, 5-12-13, 8-15-17, 7-24-25 and their multiples`],
      [T`Legs \(x\) and \(x + 7\), hypotenuse 13`, T`\(x^{2} + \left(x + 7\right)^{2} = 169\), so \(x = 5\)`],
      [T`Where is the right angle?`, T`Wall and ground, north and east, the sides of a rectangle.`],
    ],
    'w-triangles': [
      [T`Similar triangles`, T`Same angles, proportional sides.`],
      [T`Shadow problems`, T`\(\dfrac{\text{height}_{1}}{\text{shadow}_{1}} = \dfrac{\text{height}_{2}}{\text{shadow}_{2}}\)`],
      [T`Angle sum of a triangle`, T`The three angles add to \(180^{\circ}\).`],
      [T`Area of a triangle`, T`\(A = \frac{1}{2}bh\)`],
      [T`Isosceles triangle`, T`Two equal sides (and two equal angles).`],
      [T`Mirror method`, T`Equal reflection angles make similar triangles.`],
    ],
    'w-linear': [
      [T`Linear model`, T`\(y = mx + b\)`],
      [T`Slope in context`, T`Rate of change: (y units) per (x unit).`],
      [T`y-intercept in context`, T`The starting value, when \(x = 0\).`],
      [T`Interpreting the slope`, T`"For each additional [x unit], [y] increases (or decreases) by [m] [y units]."`],
      [T`When does \(y\) reach a value?`, T`Substitute it for \(y\) and solve for \(x\).`],
      [T`Negative slope in context`, T`The quantity is decreasing.`],
    ],
    'w-logs': [
      [T`Compound interest`, T`\(A = P\left(1 + \frac{r}{n}\right)^{nt}\)`],
      [T`Continuous compounding or growth`, T`\(A = Pe^{rt}\)`],
      [T`Half-life model`, T`\(A = A_{0}\left(\frac{1}{2}\right)^{t/h}\)`],
      [T`Doubling model`, T`\(A = A_{0}\cdot 2^{t/d}\)`],
      [T`Solving for the time`, T`Isolate the power, then take \(\ln\) of both sides.`],
      [T`pH`, T`\(\text{pH} = -\log\left[\text{H}^{+}\right]\); each unit is a factor of 10.`],
      [T`Decibels`, T`\(L = 10\log\frac{I}{I_{0}}\); every 10 dB is a factor of 10.`],
      [T`Earthquake magnitude`, T`\(M = \log\frac{I}{I_{0}}\); each unit is a factor of 10.`],
    ],
    'w-motion': [
      [T`Distance formula`, T`\(d = rt\)`],
      [T`Toward each other or opposite directions`, T`The distances add: \(r_{1}t + r_{2}t = D\).`],
      [T`Catching up`, T`The distances are equal; the first traveler has more time.`],
      [T`Round trip`, T`Same distance each way; the times add.`],
      [T`With or against a current`, T`Speeds \(b + c\) and \(b - c\).`],
      [T`Average speed`, T`Total distance ÷ total time (not the average of the speeds).`],
    ],
    'w-mixture': [
      [T`The two equations in any mixture problem`, T`An amount equation and a value (or ingredient) equation.`],
      [T`Amount equation`, T`The parts add to the whole: \(S + F = 40\).`],
      [T`Value equation (prices)`, T`\(70S + 90F = 77.50\left(40\right)\)`],
      [T`Percent equation (solutions)`, T`\(0.20x + 0.70\left(60\right) = 0.50y\)`],
      [T`Pure water; pure substance`, T`0%; 100%`],
      [T`Interest at two rates`, T`\(0.04x + 0.06y\) = total interest`],
    ],
    'w-systems': [
      [T`Two unknowns`, T`You need two equations.`],
      [T`Count equation`, T`\(A + C = 500\)`],
      [T`Value equation`, T`\(7A + 3.5C = 2450\)`],
      [T`Coins`, T`Value in dollars: \(0.10d + 0.25q\) = total.`],
      [T`When do two plans cost the same?`, T`Set the two cost expressions equal.`],
      [T`Checking a system answer`, T`Whole numbers of items, positive amounts, and both equations true.`],
    ],
    // ---------------- Absolute value ----------------
    'abs-value': [
      [T`Absolute value \(|a|\)`, T`The distance from \(a\) to 0 on the number line, so it is never negative: \(|-7| = 7\) and \(|7| = 7\).`],
      [T`\(|a|\) as a rule`, T`\(|a| = a\) if \(a \ge 0\), and \(|a| = -a\) if \(a \lt 0\).`],
      [T`\(-|-5|\)`, T`\(-5\): take the absolute value first, then apply the negative sign in front.`],
      [T`Bars as grouping symbols`, T`Simplify inside first: \(|3 - 8| = |-5| = 5\).`],
      [T`\(|a - b|\)`, T`The distance between \(a\) and \(b\) on the number line.`],
      [T`\(|ab|\) and \(\left|\frac{a}{b}\right|\)`, T`\(|a|\,|b|\) and \(\dfrac{|a|}{|b|}\)`],
      [T`Is \(|a + b| = |a| + |b|\)?`, T`Not always: \(|3 + (-5)| = 2\), but \(|3| + |-5| = 8\).`],
    ],
    'abs-equation': [
      [T`\(|X| = c\) with \(c \gt 0\)`, T`\(X = c\) or \(X = -c\): two equations, usually two solutions.`],
      [T`\(|X| = 0\)`, T`\(X = 0\): one solution.`],
      [T`\(|X| = \) a negative number`, T`No solution: an absolute value is never negative.`],
      [T`First step for \(a|X| + b = c\)`, T`Isolate the absolute value: subtract \(b\), then divide by \(a\).`],
      [T`\(|2x - 3| = 7\)`, T`\(2x - 3 = 7\) or \(2x - 3 = -7\), so \(x = 5\) or \(x = -2\).`],
      [T`\(|A| = |B|\)`, T`\(A = B\) or \(A = -B\).`],
      [T`\(3|x + 1| + 8 = 2\)`, T`\(|x + 1| = -2\): no solution.`],
    ],
    // ---------------- Quadratic equations & functions ----------------
    'quad-complete': [
      [T`Completing the square on \(x^{2} + bx\)`, T`Add \(\left(\frac{b}{2}\right)^{2}\): half of \(b\), squared.`],
      [T`\(x^{2} + bx + \left(\frac{b}{2}\right)^{2}\)`, T`\(\left(x + \frac{b}{2}\right)^{2}\)`],
      [T`Make \(x^{2} - 10x + c\) a perfect square`, T`\(c = 25\), giving \(\left(x - 5\right)^{2}\)`],
      [T`Solving by completing the square`, T`Divide by \(a\), move the constant, add \(\left(\frac{b}{2}\right)^{2}\) to both sides, factor, then take \(\pm\) square roots.`],
      [T`\(x^{2} - 6x + 2 = 0\)`, T`\(\left(x - 3\right)^{2} = 7\), so \(x = 3 \pm \sqrt{7}\)`],
      [T`When \(a \ne 1\)`, T`Divide every term by \(a\) first.`],
      [T`Vertex form`, T`\(y = a\left(x - h\right)^{2} + k\), vertex \((h, k)\)`],
    ],
    'quad-discriminant': [
      [T`Discriminant`, T`\(D = b^{2} - 4ac\), the part under the radical in the quadratic formula.`],
      [T`\(D \gt 0\)`, T`Two real solutions (rational if \(D\) is a perfect square). The parabola crosses the \(x\)-axis twice.`],
      [T`\(D = 0\)`, T`One real solution (a repeated root). The vertex touches the \(x\)-axis.`],
      [T`\(D \lt 0\)`, T`No real solutions (two complex ones). The parabola misses the \(x\)-axis.`],
      [T`Before reading \(a\), \(b\), \(c\)`, T`Write the equation as \(ax^{2} + bx + c = 0\) and keep the signs.`],
      [T`\(2x^{2} - 4x + 5 = 0\)`, T`\(D = 16 - 40 = -24 \lt 0\): no real solutions.`],
    ],
    'quad-form': [
      [T`Equation in quadratic form`, T`Look for an expression whose square also appears, and call it \(u\).`],
      [T`\(x^{4} - 13x^{2} + 36 = 0\)`, T`Let \(u = x^{2}\): \(u^{2} - 13u + 36 = 0\), so \(u = 4, 9\) and \(x = \pm 2, \pm 3\).`],
      [T`\(x - 5\sqrt{x} + 6 = 0\)`, T`Let \(u = \sqrt{x}\), so \(u^{2} = x\).`],
      [T`\(x^{\frac{2}{3}} - 5x^{\frac{1}{3}} + 4 = 0\)`, T`Let \(u = x^{\frac{1}{3}}\).`],
      [T`\(x^{-2} - 7x^{-1} + 12 = 0\)`, T`Let \(u = x^{-1}\).`],
      [T`The step people forget`, T`Substitute back and solve for \(x\).`],
      [T`\(u = \sqrt{x}\) comes out negative`, T`Reject it: a square root is never negative.`],
    ],
    'quad-transform': [
      [T`Vertex form`, T`\(f(x) = a\left(x - h\right)^{2} + k\): vertex \((h, k)\), axis of symmetry \(x = h\)`],
      [T`\(f(x) = -2\left(x + 3\right)^{2} + 5\)`, T`Vertex \((-3, 5)\), opens down, maximum value 5`],
      [T`\(a \gt 0\) / \(a \lt 0\)`, T`Opens up, \(k\) is the minimum / opens down, \(k\) is the maximum.`],
      [T`\(|a| \gt 1\) / \(0 \lt |a| \lt 1\)`, T`Narrower (stretch) / wider (compression).`],
      [T`Axis of symmetry from standard form`, T`\(x = -\dfrac{b}{2a}\)`],
      [T`Equation from a graph`, T`Read the vertex \((h, k)\), then substitute one more point to find \(a\).`],
    ],
    'quad-ineq': [
      [T`Solving \(ax^{2} + bx + c \lt 0\)`, T`Get 0 on one side, find the roots, then test one number in each interval.`],
      [T`Critical points`, T`The solutions of \(ax^{2} + bx + c = 0\); they split the number line.`],
      [T`\(\left(x + 2\right)\left(x - 3\right) \lt 0\)`, T`\((-2, 3)\): an upward parabola is below the axis between its roots.`],
      [T`\(\left(x + 2\right)\left(x - 3\right) \ge 0\)`, T`\((-\infty, -2] \cup [3, \infty)\)`],
      [T`Brackets or parentheses?`, T`Brackets for \(\le\) and \(\ge\) (the roots count); parentheses for \(\lt\) and \(\gt\).`],
      [T`No real roots`, T`The parabola is entirely above or below the axis: all real numbers or no solution.`],
    ],
    // ---------------- Relations & functions (added) ----------------
    'fn-piecewise': [
      [T`Piecewise function`, T`A function given by different formulas on different parts of its domain.`],
      [T`Evaluating \(f(a)\)`, T`Find the one row whose condition \(a\) satisfies, and use only that formula.`],
      [T`At a boundary like \(x = 2\)`, T`Use the row whose condition includes it (\(\le\) or \(\ge\)).`],
      [T`Graphing a piece`, T`Graph its formula only over its interval: closed dot for \(\le, \ge\); open dot for \(\lt, \gt\).`],
      [T`\(|x|\) as a piecewise function`, T`\(x\) if \(x \ge 0\), and \(-x\) if \(x \lt 0\).`],
      [T`Can the conditions overlap?`, T`No. Each \(x\) may belong to only one piece, or it would not be a function.`],
    ],
    'fn-transform': [
      [T`\(f(x) + k\)`, T`Shift up \(k\) units (down if \(k \lt 0\)).`],
      [T`\(f(x - h)\)`, T`Shift right \(h\) units. \(f(x + h)\) shifts left: the opposite of the sign you see.`],
      [T`\(-f(x)\)`, T`Reflect across the \(x\)-axis.`],
      [T`\(f(-x)\)`, T`Reflect across the \(y\)-axis.`],
      [T`\(a\,f(x)\)`, T`Vertical stretch if \(|a| \gt 1\); compression if \(0 \lt |a| \lt 1\).`],
      [T`\(f(bx)\)`, T`Horizontal compression by a factor of \(\frac{1}{b}\) if \(b \gt 1\); stretch if \(0 \lt b \lt 1\).`],
      [T`\(g(x) = a\,f(x - h) + k\)`, T`The point \((p, q)\) on \(f\) moves to \((p + h,\ aq + k)\) on \(g\).`],
      [T`Basic graphs to know`, T`\(x^{2}\), \(x^{3}\), \(\sqrt{x}\), \(\sqrt[3]{x}\), \(|x|\), \(\frac{1}{x}\)`],
    ],
    // ---------------- Word problems (added) ----------------
    'w-quadratic': [
      [T`Projectile height`, T`\(h = -16t^{2} + v_{0}t + h_{0}\) (feet, seconds)`],
      [T`When does it hit the ground?`, T`Solve \(h = 0\) and keep the positive time.`],
      [T`When is it at height \(H\)?`, T`Solve \(h = H\); usually two times, going up and coming down.`],
      [T`Maximum height`, T`At the vertex: \(t = -\dfrac{b}{2a}\), then evaluate \(h\) there.`],
      [T`Maximum area with a fixed perimeter \(P\)`, T`\(A = x\left(\frac{P}{2} - x\right)\); the vertex gives a square.`],
      [T`Revenue`, T`price × number sold; write both in terms of one variable.`],
      [T`Maximum or minimum?`, T`\(a \lt 0\): the vertex is a maximum. \(a \gt 0\): a minimum.`],
    ],
    // ---------------- Part III: linear equations & inequalities ----------------
    'lq-strategy': [
      [T`General strategy for linear equations`, T`Clear fractions, distribute, combine like terms on each side, get the variable on one side, then divide.`],
      [T`Conditional equation`, T`True for exactly one value: one solution.`],
      [T`Identity`, T`True for every value, like \(2(x + 1) = 2x + 2\): all real numbers.`],
      [T`Contradiction`, T`The variable drops out and leaves a false statement like \(3 = 7\): no solution.`],
      [T`Fractions in an equation`, T`Multiply both sides by the LCD of all the fractions.`],
      [T`Decimals in an equation`, T`Multiply both sides by 10, 100, ... to make every coefficient a whole number.`],
      [T`Nested grouping`, T`Work from the innermost parentheses out.`],
    ],
    'lq-problems': [
      [T`Problem-solving steps`, T`Read, identify what you're looking for, name it with a variable, translate to an equation, solve, check, answer with a sentence.`],
      [T`Consecutive integers`, T`\(n\), \(n + 1\), \(n + 2\)`],
      [T`Consecutive odd (or even) integers`, T`\(n\), \(n + 2\), \(n + 4\)`],
      [T`Percent equation`, T`amount = percent × base`],
      [T`Markup and discount`, T`Markup: price = cost + rate × cost. Discount: sale price = original − rate × original.`],
      [T`Simple interest`, T`\(I = Prt\) (\(r\) as a decimal, \(t\) in years)`],
      [T`Commission`, T`commission = rate × total sales`],
    ],
    'lq-formulas': [
      [T`Solving a formula for a variable`, T`Treat the other letters as numbers and isolate the one you want.`],
      [T`\(A = \frac{1}{2}bh\) for \(h\)`, T`\(h = \dfrac{2A}{b}\)`],
      [T`\(ax + by = c\) for \(y\)`, T`\(y = \dfrac{c - ax}{b}\)`],
      [T`Angles of a triangle`, T`They add to \(180^{\circ}\).`],
      [T`Complementary / supplementary angles`, T`Sum to \(90^{\circ}\) / sum to \(180^{\circ}\).`],
      [T`Area of a trapezoid`, T`\(A = \frac{1}{2}h\left(b + B\right)\)`],
      [T`Perimeter of a rectangle`, T`\(P = 2L + 2W\)`],
    ],
    'lq-applications': [
      [T`Value of coins`, T`number × value of each (in dollars): \(0.10d + 0.25q\)`],
      [T`Ticket and stamp problems`, T`Number equation plus a value equation; write one count in terms of the other.`],
      [T`Mixture: price per pound`, T`pounds × price, added: \(4x + 7\left(20 - x\right) = 5.50\left(20\right)\)`],
      [T`Mixture: solutions`, T`amount of solution × concentration = amount of pure substance.`],
      [T`Uniform motion`, T`\(d = rt\). Opposite directions or toward each other: distances add. Same route: distances are equal.`],
      [T`Mixed units`, T`Convert minutes to hours: 45 min = \(\frac{3}{4}\) h.`],
    ],
    'lq-linear-ineq': [
      [T`Multiplying or dividing an inequality by a negative`, T`Reverse the inequality sign.`],
      [T`Interval notation for \(x \gt 3\)`, T`\((3, \infty)\)`],
      [T`Interval notation for \(x \le -1\)`, T`\((-\infty, -1]\)`],
      [T`Bracket or parenthesis?`, T`Bracket (closed dot) for \(\le, \ge\); parenthesis (open dot) for \(\lt, \gt\) and always at \(\pm\infty\).`],
      [T`at least / at most`, T`\(\ge\) / \(\le\)`],
      [T`Break-even or profit`, T`Profit = revenue − cost; for a profit, revenue \(\gt\) cost.`],
    ],
    'lq-compound': [
      [T`"And" (intersection)`, T`Both must be true: the overlap. \(-2 \lt x \le 5\) is \((-2, 5]\).`],
      [T`"Or" (union)`, T`Either can be true: \(x \lt -1\) or \(x \ge 4\) is \((-\infty, -1) \cup [4, \infty)\).`],
      [T`Solving a double inequality`, T`Do the same thing to all three parts; reverse both signs if you divide by a negative.`],
      [T`\(-3 \lt 2x + 1 \le 7\)`, T`\(-2 \lt x \le 3\), or \((-2, 3]\)`],
      [T`An "and" with no overlap`, T`No solution.`],
      [T`An "or" that covers the whole line`, T`All real numbers, \((-\infty, \infty)\).`],
    ],
    'lq-absineq': [
      [T`\(|X| \lt c\) (with \(c \gt 0\))`, T`\(-c \lt X \lt c\): an "and", one interval between two points.`],
      [T`\(|X| \gt c\) (with \(c \gt 0\))`, T`\(X \lt -c\) or \(X \gt c\): an "or", two rays.`],
      [T`First step`, T`Isolate the absolute value before splitting.`],
      [T`\(|x - 3| \le 5\)`, T`\(-2 \le x \le 8\), or \([-2, 8]\)`],
      [T`\(|X| \lt\) a negative number`, T`No solution.`],
      [T`\(|X| \gt\) a negative number`, T`All real numbers.`],
      [T`Tolerance problems`, T`"Within \(t\) of \(m\)" means \(|x - m| \le t\).`],
    ],
  };
})(typeof window !== 'undefined' ? window : globalThis);
